//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameCoding
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GameCoding()
        {
            this.StudentCourses = new HashSet<StudentCours>();
        }
    
        public int Id { get; set; }
        public string StemId { get; set; }
        public int BranchId { get; set; }
        public string AgeRangeId { get; set; }
        public int GameId { get; set; }
    
        public virtual AgeRange AgeRange { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual STEM STEM { get; set; }
        public virtual Game Game { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentCours> StudentCourses { get; set; }
    }
}
