//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginHistory
    {
        public int Id { get; set; }
        public int userId { get; set; }
        public string username { get; set; }
        public System.DateTime loginDateTimeStamp { get; set; }
        public Nullable<System.DateTime> logoutDateTimeStamp { get; set; }
        public decimal totalCashAmount { get; set; }
    
        public virtual User User { get; set; }
    }
}
